/**
*  This file is an example localization for Portable Contacts
*/

$(document).ready(function() {

// default language
  $.global.culture ="en";

  $.global.localize("poco","en", {
    anniversary :"Anniversary",
    anniversary_Placeholder :"1970-05-05",
    birthday :"Birthday",
    birthday_Placeholder :"1972-06-02",
    connected :"Connected",
    connected_Placeholder :"True/False",
    displayName :"Display Name",
    displayName_Placeholder :"Ori Pekelman",
    emails_Legend :"Emails",
    email_number_Placeholder :"Email address",
    email_type_Placeholder :"ori@af83.com",
    familyName :"Family Name",
    familyName_Placeholder :"Pekelman",
    gender :"Gender",
    gender_Placeholder :"Male/Female/Unknown",
    givenName :"Given Name",
    givenName_Placeholder :"Ori",
    honorificPrefix :"Honorific Prefix",
    honorificPrefix_Placeholder :"Mr.",
    honorificSuffix :"Honorific Suffix",
    honorificSuffix_Placeholder :"Esquire",
    id :"id",
    id_Placeholder :"98756897",
    middleName :"Middle Name",
    middleName_Placeholder :"Aharon",
    name_Legend :"Name",
    note :"Note",
    note_Placeholder :"For he is a joly good fellow",
    number :"Number",
    phones_Legend :"Phones",
    phone_number_Placeholder :"phone_number_Placeholder",
    phone_type_Placeholder :"phone_type_Placeholder",
    preferredUsername :"Preferred Username",
    preferredUsername_Placeholder:"preferredUsername_Placeholder",
    primary :"Primary",
    primary_Placeholder :"primary_Placeholder",
    published :"Published",
    published_Placeholder :"published_Placeholder",
    type :"Type",
    updated :"Updated",
    updated_Placeholder :"updated_Placeholder",
    utcOffset :"UTC Offset",
    utcOffset_Placeholder :"Time zone: GMT +2",
    photo_number_Placeholder     :"http///www.example.com/avatars/myavatar.png",
    photo_type_Placeholder       :"Avatar",
    primary_Placeholder          :"True/False",
    addresses_Legend             :"Addresses",
    country                      :"Country",
    country_Placeholder          :"country_Placeholder",
    formatted                    :"Formatted",
    formatted_Placeholder        :"formatted_Placeholder",
    postalcode                   :"Postal code",
    postalcode_Placeholder       :"75002",
    region                       :"Region",
    region_Placeholder           :"Ile-de-France",
    streetAddress                :"Street Address",
    streetAddress_Placeholder    :"15 rue Possonière",
    type                         :"Type",
    url_type_Placeholder         :"Blog/Homepage/",
    photos_Legend                :"Photos",
    urls_Legend                  :"Urls",
    ims_Legend                   :"Instant Messaging",
    aboutMe                               :"aboutMe",
    aboutMe_Placeholder                   :"aboutMe_Placeholder",
    accounts_Legend                       :"accounts_Legend",
    activities                            :"activities",
    activity                              :"activity",
    activity_Placeholder                  :"activity_Placeholder",
    bodyType_build_Placeholder            :"bodyType_build_Placeholder ",
    bodyType_Legend                       :"bodyType_Legend",
    books                                 :"books",
    build                                 :"build",
    cars                                  :"cars",
    children                              :"children",
    children_Placeholder                  :"children_Placeholder",
    currentLocation                       :"currentLocation",
    currentLocation_Placeholder           :"currentLocation_Placeholder",
    drinker                               :"drinker",
    drinker_Placeholder                   :"drinker_Placeholder",
    ethnicity                             :"ethnicity",
    ethnicity_Placeholder                 :"ethnicity_Placeholder",
    eyeColor                              :"eyeColor",
    eyeColor_Placeholder                  :"eyeColor_Placeholder",
    fashion                               :"fashion",
    fashion_Placeholder                   :"fashion_Placeholder",
    food                                  :"food",
    hairColor                             :"hairColor",
    hairColor_Placeholder                 :"hairColor_Placeholder",
    happiestWhen                          :"happiestWhen",
    happiestWhen_Placeholder              :"happiestWhen_Placeholder",
    height                                :"height ",
    height_Placeholder                    :"height_Placeholder ",
    heroes                                :"heroes ",
    humor                                 :"humor",
    humor_Placeholder                     :"humor_Placeholder",
    interests                             :"interests",
    jobInterests                          :"jobInterests",
    jobInterests_Placeholder              :"jobInterests_Placeholder",
    languages                             :"languages",
    livingArrangement                     :"livingArrangement",
    livingArrangement_Placeholder         :"livingArrangement_Placeholder",
    lookingFor                            :"lookingFor",
    lookingFor_Placeholder                :"lookingFor_Placeholder",
    movies                                :"movies ",
    music                                 :"music",
    organizations_Legend                  :"organizations_Legend",
    pets                                  :"pets",
    pets_Placeholder                      :"pets_Placeholder",
    politicalViews                        :"politicalViews ",
    politicalViews_Placeholder            :"politicalViews_Placeholder ",
    profileSong                           :"profileSong ",
    profileSong_Placeholder               :"profileSong_Placeholder ",
    profileVideo                          :"profileVideo",
    profileVideo_Placeholder              :"profileVideo_Placeholder",
    quotes                                :"quotes ",
    relationshipStatus                    :"relationshipStatus ",
    relationshipStatus_Placeholder        :"relationshipStatus_Placeholder ",
    religion                              :"religion",
    religion_Placeholder                  :"religion_Placeholder",
    romance                               :"romance",
    romance_Placeholder                   :"romance_Placeholder",
    scaredOf                              :"scaredOf",
    scaredOf_Placeholder                  :"scaredOf_Placeholder",
    sexualOrientation                     :"sexualOrientation",
    sexualOrientation_Placeholder         :"sexualOrientation_Placeholder",
    smoker                                :"smoker ",
    smoker_Placeholder                    :"smoker_Placeholder ",
    spokenLanguages                       :"spokenLanguages",
    sports                                :"sports ",
    status                                :"status ",
    status_Placeholder                    :"status_Placeholder ",
    turnOffs                              :"turnOffs",
    turnOns                               :"turnOns",
    tvShows                               :"tvShows",
    weight                                :"weight ",
    weight_Placeholder                    :"weight_Placeholder ",
    aboutMe                               :"aboutMe",
    account_domain_Placeholder             :"account_domain_Placeholder",
    departement                            :"departement",
    description                            :"description",
    domain                                 :"domain",
    enddate                                :"enddate",
    endDate_Placeholder                    :"endDate_Placeholder",
    location                               :"location",
    location_Placeholder                   :"location_Placeholder",
    name                                   :"name",
    organization_departement_Placeholder   :"organization_departement_Placeholder",
    organization_name_Placeholder          :"organization_name_Placeholder",
    organization_title_Placeholder         :"organization_title_Placeholder",
    organization_description_Placeholder    :"organization_description_Placeholder",
    startdate                              :"startdate",
    startDate_Placeholder                  :"startDate_Placeholder",
    title                                  :"title",
    userid                                 :"userid",
    userid_Placeholder                     :"userid_Placeholder",
    username                               :"username",
    username_Placeholder                   :"username_Placeholder",

  });

  $.global.localize("poco","fr", {
    anniversary :"Anniversaire",
    anniversary_Placeholder :"1970-05-05",
    birthday :"Naissance",
    birthday_Placeholder :"1972-06-02",
    connected :"Connecté",
    connected_Placeholder :"True/False",
    displayName :"Nom affiché",
    displayName_Placeholder :"Ori Pekelman",
    emails_Legend :"Email",
    email_number_Placeholder :"email_number_Placeholder",
    email_type_Placeholder :"email_type_Placeholder",
    familyName :"familyName",
    familyName_Placeholder :"familyName_Placeholder",
    gender :"gender",
    gender_Placeholder :"gender_Placeholder",
    givenName :"Prénom",
    givenName_Placeholder :"givenName_Placeholder",
    honorificPrefix :"honorificPrefix",
    honorificPrefix_Placeholder :"honorificPrefix_Placeholder",
    honorificSuffix :"honorificSuffix",
    honorificSuffix_Placeholder :"honorificSuffix_Placeholder",
    id :"id",
    id_Placeholder :"id_Placeholder",
    middleName :"middleName",
    middleName_Placeholder :"middleName_Placeholder",
    name_Legend :"name_Legend",
    note :"note",
    note_Placeholder :"note_Placeholder",
    number :"number",
    phones_Legend :"phones_Legend",
    phone_number_Placeholder :"phone_number_Placeholder",
    phone_type_Placeholder :"phone_type_Placeholder",
    preferredUsername :"preferredUsername",
    preferredUsername_Placeholder:"preferredUsername_Placeholder",
    primary :"primary",
    primary_Placeholder :"primary_Placeholder",
    published :"published",
    published_Placeholder :"published_Placeholder",
    type :"type",
    updated :"updated",
    updated_Placeholder :"updated_Placeholder",
    utcOffset :"utcOffset",
    utcOffset_Placeholder :"utcOffset_Placeholder",
    photo_number_Placeholder     :"photo_number_Placeholder",
    photo_type_Placeholder       :"photo_type_Placeholder",
    primary_Placeholder          :"primary_Placeholder",
    addresses_Legend             :"addresses_Legend",
    country                      :"country",
    country_Placeholder          :"country_Placeholder",
    formatted                    :"formatted",
    formatted_Placeholder        :"formatted_Placeholder",
    postalcode                   :"postalcode",
    postalcode_Placeholder       :"postalcode_Placeholder",
    region                       :"region",
    region_Placeholder           :"region_Placeholder",
    streetAddress                :"streetAddress",
    streetAddress_Placeholder    :"streetAddress_Placeholder",
    type                         :"type",
    url_type_Placeholder         :"url_type_Placeholder",
    
  });

});
